policy: "classic"
classic_conf {
  groups {
    name: "autodrive"
    processor_num: 1
    tasks { name: "perception" prio: 5 }
    tasks { name: "fusion" prio: 5 }
    tasks { name: "planning" prio: 5 }
    tasks { name: "control" prio: 5 }
    tasks { name: "control_audit" prio: 5 }
  }
}
